// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb1LOUMxvSIud0xrdxgag4bXb9GoJDzz4',
    appId: '1:262419846644:web:c329f235e6ddf66892d5a1',
    messagingSenderId: '262419846644',
    projectId: 'thebronx-378ae',
    authDomain: 'thebronx-378ae.firebaseapp.com',
    storageBucket: 'thebronx-378ae.firebasestorage.app',
    measurementId: 'G-XGW8J6VJYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRMWfM0ARRDM9tysknfmEZhdStktC_vpk',
    appId: '1:262419846644:android:56a80e95bf9523c492d5a1',
    messagingSenderId: '262419846644',
    projectId: 'thebronx-378ae',
    storageBucket: 'thebronx-378ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxOkJQj0Z9A5A7ZWM8s3-28VvcwUDcheI',
    appId: '1:262419846644:ios:213b003cd63c726192d5a1',
    messagingSenderId: '262419846644',
    projectId: 'thebronx-378ae',
    storageBucket: 'thebronx-378ae.firebasestorage.app',
    iosBundleId: 'com.example.svdThebronx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxOkJQj0Z9A5A7ZWM8s3-28VvcwUDcheI',
    appId: '1:262419846644:ios:213b003cd63c726192d5a1',
    messagingSenderId: '262419846644',
    projectId: 'thebronx-378ae',
    storageBucket: 'thebronx-378ae.firebasestorage.app',
    iosBundleId: 'com.example.svdThebronx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb1LOUMxvSIud0xrdxgag4bXb9GoJDzz4',
    appId: '1:262419846644:web:ea3a76e036fc501792d5a1',
    messagingSenderId: '262419846644',
    projectId: 'thebronx-378ae',
    authDomain: 'thebronx-378ae.firebaseapp.com',
    storageBucket: 'thebronx-378ae.firebasestorage.app',
    measurementId: 'G-K1ZC6BNZLS',
  );
}
